### ISSUE TITLE
having issues with the dependencies 

### ISSUE THREAD

**Issue by Chainedtheno1** [AJaySi/AI-Writer#136] opened 2024-10-21 06:44 UTC
Whenever i try to run the alwrity.py i get missing modules etc. i tried my best to manually install all of thema dn troubleshoot but now im stuck with this for quite some time

![Screenshot 2024-10-21 144353](https://github.com/user-attachments/assets/5f654055-6b6f-470a-b1de-aea901a80610)

please and thank you

**Comment by AJaySi** [comment] 2024-10-21 07:29
Hello, 
Lets work this through. Please try the below options.

1). Trying it out in a virtual env with python -m venv venv and then activating the venv will be a cleaner option.

2). Check with typing python and then write 'From tavily import TavilyClient'. Does it give the same ModuleNotFoundError ?

3). Also, try 'pip install tavily-python' in this same dir as AI-Writer folder.
Let me know the outputs and we can some more things. Keep at it.

**Comment by Chainedtheno1** [comment] 2024-10-21 08:08
i attempteed the virtual env and i managed to re-install the venv. but now another module is saying its missing.
![Uploading Screenshot 2024-10-21 160842.png…]()

**Comment by AJaySi** [comment] 2024-10-21 09:33
Hmmm, the issue is with external module called yfinance. This behavior is not present at my end or reported otherwise.
https://github.com/ranaroussi/yfinance/issues/1942

Try: pip install yfinance with -U option, which will update it use latest version of it.

**Comment by AJaySi** [comment] 2024-10-21 09:36
https://github.com/ranaroussi/yfinance/issues/2093

**Comment by Chainedtheno1** [comment] 2024-10-21 10:35
aight thanks bro. i managed to fix it by reverting to an older version of yfinance(0.2.18)

**Comment by tukangcode** [comment] 2024-11-02 08:51
> aight thanks bro. i managed to fix it by reverting to an older version of yfinance(0.2.18)

hi how you revert to older version what is commad

**Comment by AJaySi** [comment] 2024-11-04 02:06
Hello @tukangcode  
You can do pip install -r requirements, once again. The issue is fixed in yfinance.
Else you can also do: pip install yfinance==0.2.44

**Comment by AJaySi** [comment] 2024-11-04 12:35
Closing this as yfinance has fixed the error in latest release.

**Closed by AJaySi** 2024-11-04 12:35 UTC
