### ISSUE TITLE
Blog Generation Issue on latest updated code 

### ISSUE THREAD

**Issue by umesh070** [AJaySi/AI-Writer#26] opened 2024-04-08 13:15 UTC
After cloning the latest code update, I attempted to run it but encountered an issue (mentioned below) where the blog post generation was failing. Could you kindly assist me in troubleshooting this matter? Your help is greatly appreciated. Thank you.

ERROR|google_serp_search.py:309:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Windows\\System32\\AI-Blog-Writer\\AI-Writer\\workspace\\web_research_reports\\google_guideline_in_ai_contents_2024-04-08_18-29-21'
ERROR|google_serp_search.py:309:save_in_file| Error occurred while writing to the file: [Errno 2] No such file or directory: 'C:\\Windows\\System32\\AI-Blog-Writer\\AI-Writer\\workspace\\web_research_reports\\google_guideline_in_ai_contents_2024-04-08_18-29-21'
INFO|blog_from_google_serp.py:36:write_blog_google_serp| Generating blog and FAQs from Google web search results.
ERROR|main_text_generation.py:150:read_llm_parameters| An unexpected error occurred: 'charmap' codec can't decode byte 0x9d in position 2087: character maps to <undefined>
ERROR|main_text_generation.py:55:llm_text_gen| Failed to read LLM parameters: 'charmap' codec can't decode byte 0x9d in position 2087: character maps to <undefined>
ERROR|blog_from_google_serp.py:41:write_blog_google_serp| Exit: Failed to get response from LLM: 'charmap' codec can't decode byte 0x9d in position 2087: character maps to <undefined>

**Comment by AJaySi** [comment] 2024-04-08 13:50
Unable to reproduce it. Maybe, trying cloing again.. 
Can you details your steps  ?

**Comment by umesh070** [comment] 2024-04-08 15:27
I cloned the updated code again on a different laptop and got the different issue mentioned in the below photo. 

![WhatsApp Image 2024-04-08 at 20 14 59_92b3653f](https://github.com/AJaySi/AI-Writer/assets/150319020/1e5018d8-38bb-4355-bb59-230837e592d5)

**Comment by AJaySi** [comment] 2024-04-12 03:12
@umesh070 please close the issue if its done ?
Thanks.

**Comment by umesh070** [comment] 2024-04-12 13:48
This is the error I am getting in the new code.

![Screenshot (13)](https://github.com/AJaySi/AI-Writer/assets/150319020/6a6fad1e-56d4-490a-ab08-b8c026f0fa6c)

**Comment by umesh070** [comment] 2024-04-12 14:09
Hello, @AJaySi 

I have run the new code again. Now the previous error is solved. Now it's giving one blog after the SERP research.

**Comment by AJaySi** [comment] 2024-04-12 14:17
@umesh070 
Please check again, i updated the code.

**Comment by umesh070** [comment] 2024-04-12 14:23
No changes yet.  Same result as above to write a blog from keywords.

**Closed** 2024-04-12 14:44 UTC
